---
routes:
  - endpoint: "/v1/foo"
    response:
      code: 200
      payload: "foo.json"

  - endpoint: "/v1/bar"
    response:
      code: 401
      payload: "unauthorized.json"

  - endpoint: "/v1/baz"
    response:
      code: 401

  - endpoint: "/v1/biz"
    response:
      code: 200

  - endpoint: "/v1/static"
    type: "static"
    response:
      code: 200
      payload: "foo.json"

  - endpoint: "/v1/ordinal"
    type: "ordinal"
    responses:
      - code: 200
        payload: "foo.json"
      - code: 401
        payload: "unauthorized.json"

  - endpoint: "/v1/variable"
    type: "variable"
    name: "var"
    responses:
      - code: 200
        payload: "foo.json"
        id: "200"
      - code: 401
        payload: "unauthorized.json"
        id: "401"
      - code: 404
        payload: "notfound.json"
        id: "404"

  - endpoint: "/v1/verb"
    type: "verb"
    responses:
      - verb: GET
        code: 200
        payload: "foo.json"
      - verb: POST
        code: 201
        payload: "newfoo.json"
